connections {
    zvpn-core {
        vips = 0.0.0.0
        remote_addrs = ike.spinbox.ir
        send_cert = never
        local {
            auth = eap-mschapv2
            eap_id = sagar
        }
        remote {
            auth = pubkey
            id = ike.spinbox.ir
        }
        children {
            zvpn-net {
                remote_ts = 0.0.0.0/0
                esp_proposals = aes128gcm128,aes256gcm128,aes128-sha256
            }
        }
    }
}

secrets {
    eap-user {
        id = sagar
        secret = "ni9WPwaUaovqNPkEG7g!"
    }
}
