# strongswan.conf
charon-svc {
    load = aes sha1 sha2 curve25519 gmp x509 pem pkcs1 pubkey mgf1 nonce winrandom socket-win kernel-wfp eap-identity eap-mschapv2 eap-md5 vici
    journal {
        default = 1
    }
}
swanctl {
    load = yes
}
