# strongswan.conf
charon-svc {
    load_modular = yes
    plugins {
        socket-win { load = yes }
        kernel-wfp { load = yes }
        vici { load = yes }
        winrandom { load = yes }
        nonce { load = yes }
        aes { load = yes }
        sha1 { load = yes }
        sha2 { load = yes }
        curve25519 { load = yes }
        gmp { load = yes }
        x509 { load = yes }
        pem { load = yes }
        pkcs1 { load = yes }
        pubkey { load = yes }
        mgf1 { load = yes }
        eap-identity { load = yes }
        eap-mschapv2 { load = yes }
        eap-md5 { load = yes }
    }
}
